export enum MODES {
  CHOSE_MODE,
  PVP_MODE,
  PVE_MODE,
  PLAY_AI,
  PLAY_WITH_HUMAN,
  PLAY_TREASURE_QUEST,
  PLAY_TOURNAMENT,
}

export enum AI_PLAY_MODE {
  BEGINNER = 1,
  ROOKIE,
  AMATEUR,
  INTERMEDIATE,
  PROFESSIONAL,
  WORLD_CLASS,
  MASTER,
  GRAND_MASTER,
  LEGEND,
  IMMORTAL,
}

export enum TREASURE_QUEST_MODES {
  REV_SHARE,
  SOLO_QUEST,
}

export enum GAME_MODES {
  TWO_DIMENSION = "2D",
  THREE_DIMESION = "3D",
  WARFRONT = "WARFRONT"
}

export const INITIAL_FEN = `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1`;